export const mockApiResponse = {
    "query": "is there any paper avaible on phone device rag.",
    "topics": [
        "is there any paper avaible on phone device rag."
    ],
    "discovered": 10,
    "deduped": 10,
    "attempted": 3,
    "saved": 3,
    "skipped": 0,
    "failed": 0,
    "results": [
        {
            "paper_id": "paper_d752e1d83ff1332d",
            "status": "saved",
            "reason": "",
            "pdf_path": "C:\\Users\\faizk\\projects\\New folder\\data\\pdf\\paper_d752e1d83ff1332d.pdf",
            "metadata_path": "C:\\Users\\faizk\\projects\\New folder\\data\\metadata\\paper_d752e1d83ff1332d.json"
        },
        {
            "paper_id": "paper_60457fb9534d185d",
            "status": "saved",
            "reason": "",
            "pdf_path": "C:\\Users\\faizk\\projects\\New folder\\data\\pdf\\paper_60457fb9534d185d.pdf",
            "metadata_path": "C:\\Users\\faizk\\projects\\New folder\\data\\metadata\\paper_60457fb9534d185d.json"
        },
        {
            "paper_id": "paper_0c83cadc1531d267",
            "status": "saved",
            "reason": "",
            "pdf_path": "C:\\Users\\faizk\\projects\\New folder\\data\\pdf\\paper_0c83cadc1531d267.pdf",
            "metadata_path": "C:\\Users\\faizk\\projects\\New folder\\data\\metadata\\paper_0c83cadc1531d267.json"
        }
    ],
    "aggregated_extraction": {
        "output_json_path": "C:\\Users\\faizk\\projects\\New folder\\data\\all_downloaded_pdfs.json",
        "processed_count": 3,
        "failed_count": 0,
        "failed": [],
        "papers": [
            {
                "conversation_id": "ac3db17b-da95-40ef-9f9c-54f63168ea52",
                "paper_id": "paper_1ab72c881631629f",
                "title": "RAG System for Supporting Japanese Litigation",
                "topic": "legal language models",
                "abstract": "This study discusses the essential components that a Retrieval-Augmented Generation (RAG)-based LLM system should possess in order to support Japanese medical litigation procedures complying with legal norms. In litigation, expert commissioners, such as physicians, architects, accountants, and engineers, provide specialized knowledge to help judges clarify points of dispute. When considering the substitution of these expert roles with a RAG-based LLM system, the constraint of strict adherence to legal norms is imposed. Specifically, three requirements arise: (1) the retrieval module must retrieve appropriate external knowledge relevant to the disputed issues in accordance with the principle prohibiting the use of private knowledge, (2) the responses generated must originate from the context provided by the RAG and remain faithful to that context, and (3) the retrieval module must reference external knowledge with appropriate timestamps corresponding to the issues at hand. This paper discusses the design of a RAG-based LLM system that satisfies these requirements.",
                "introduction": "In recent years, large language models (LLMs) have demonstrated remarkable advancements in their capabilities, leading to a growing movement toward their implementations into professional domains such as medicine and law. Since they are trained on extensive large text corpora, LLMs acquire a broad collection of knowledge throughout the training process [1, 2]. However, LLMs do not retain up-to-date information about events that occurred after their training period, and their knowledge of highly specialized or less common domains is not necessarily adequate. For these reasons, in professional domains such as legal[3] and medicine[4] , recent research has increasingly explored the use of Retrieval-Augmented Generation (RAG) approaches, which exploits external knowledge to generate high-quality responses.",
                "methodology": "",
                "results": "",
                "conclusion": "",
                "claims": [
                    "A RAGbased LLM system should possess essential components to support Japanese medical litigation procedures complying with legal norms.",
                    "Expert commissioners, such as physicians, architects, accountants, and engineers, provide specialized knowledge to help judges clarify points of dispute in litigation.",
                    "A RAGbased LLM system must retrieve appropriate external knowledge relevant to the disputed issues in accordance with the principle prohibiting the use of private knowledge.",
                    "The responses generated by a RAGbased LLM system must originate from the context provided by the RAG and remain faithful to that context.",
                    "The retrieval module of a RAGbased LLM system must reference external knowledge with appropriate timestamps corresponding to the issues at hand.",
                    "A RAGbased LLM system can satisfy the requirements for supporting Japanese medical litigation procedures complying with legal norms."
                ],
                "methods": [],
                "datasets": [],
                "figures": [
                    {
                        "figure_id": "fig_1",
                        "caption": "process of civil litigation\nwitnesses, and offer explanations to judges to aid in assessing the reliability of evidence and witness\ntestimonies presented by the parties. Particularly, because fact-finding by judges in medical litigation\nrequires domain-specific medical expertise, identifying the matters that should be subject to expert\ntestimony demands extensive referencing and analysis of a large volume of legal and medical claims\nand related documents. Consequently, the workload in this proce",
                        "summary": "This figure illustrates the complex process of civil litigation, highlighting the extensive referencing and analysis required for medical cases."
                    },
                    {
                        "figure_id": "fig_2",
                        "caption": "Overview of the a RAG-based LLM System\nconsider the expert knowledge that was valid at the relevant point in time.\nBased on the above, this study addresses the realization of a \"norm-compliant RAG\" system, focusing\non: (1)controlling knowledge sources in compliance with procedural requirements concerning the use\nof expert knowledge, (2)attribution and faithfulness of generated responses to their information sources;\nand (3)appropriateness of the published time of referenced sources.\n3. Related W",
                        "summary": "This figure illustrates a RAG-based LLM system that incorporates expert knowledge in a norm-compliant manner."
                    }
                ],
                "tables": [
                    {
                        "table_id": "table_5",
                        "caption": "Conclusion\nWe are developing a RAG-based LLM system to support medical litigation proceedings in Japan. Such\na system must not just present accurate information, but also provide legally compliant responses to\nsupport expert testimony. To accommodate the requirements, we propose aspects of \"conformance\nto the norm\" that a legal RAG system should satisfy. Specifically, we propose three aspects: (1)\ncontrolling knowledge sources in compliance with procedural requirements concerning the use of\nexpe",
                        "insight": "The key finding is that a legal RAG system must provide legally compliant responses to support expert testimony."
                    }
                ],
                "citations": [
                    "F. Petroni, T. Rocktäschel, S. Riedel, P. Lewis, A. Bakhtin, Y. Wu, A. Miller, Language Models as",
                    "J. Wei, Y. Tay, R. Bommasani, C. Raffel, B. Zoph, S. Borgeaud, D. Yogatama, M. Bosma, D. Zhou,",
                    "V. Magesh, F. Surani, M. Dahl, M. Suzgun, C. D. Manning, D. E. Ho, Hallucination-Free? Assessing",
                    "Y.-W. Chu, K. Zhang, C. Malon, M. R. Min, Reducing Hallucinations of Medical Multimodal Large",
                    "G. Okanari, Saibankan no shichi riyou no kinshi (the prohibition of judge's use of private",
                    "E. Sugiyama, Saibankan niyoru senmonchishiki no shushu to riyou (collection and use of expert",
                    "Y. Shirai, Mijukuji Moumakusyou to Ishi no Kashitu (Misdiagnosis of retinopathy of prematurity",
                    "A. Albalak, Y. Elazar, S. M. Xie, S. Longpre, N. Lambert, X. Wang, N. Muennighoff, B. Hou, L. Pan,",
                    "K. Li, O. Patel, F. Viégas, H. Pfister, M. Wattenberg, Inference-Time Intervention: Eliciting Truthful",
                    "P. Manakul, A. Liusie, M. Gales, SelfCheckGPT: Zero-Resource Black-Box Hallucination Detection",
                    "X. Zhang, B. Peng, Y. Tian, J. Zhou, L. Jin, L. Song, H. Mi, H. Meng, Self-Alignment for Factuality:",
                    "Y. Wang, R. G. Reddy, Z. M. Mujahid, A. Arora, A. Rubashevskii, J. Geng, O. M. Afzal, L. Pan,",
                    "P. Lewis, E. Perez, A. Piktus, F. Petroni, V. Karpukhin, N. Goyal, H. Küttler, M. Lewis, W. tau Yih,",
                    "Y. Gao, Y. Xiong, X. Gao, K. Jia, J. Pan, Y. Bi, Y. Dai, J. Sun, M. Wang, H. Wang, Retrieval-Augmented",
                    "S. T. I. Tonmoy, S. M. M. Zaman, V. Jain, A. Rani, V. Rawte, A. Chadha, A. Das, A Comprehensive",
                    "W. Zhang, J. Zhang, Hallucination Mitigation for Retrieval-Augmented Large Language Models: A",
                    "G. Pruthi, F. Liu, S. Kale, M. Sundararajan, Estimating Training Data Influence by Tracing Gradient",
                    "T. A. Chang, D. Rajagopal, T. Bolukbasi, L. Dixon, I. Tenney, Scalable Influence and Fact Tracing"
                ]
            },
            {
                "conversation_id": "571c5ea9-d141-4233-a0b8-a84709f3d7f2",
                "paper_id": "paper_8da96723e8a468a0",
                "title": "RAG-Gym: Systematic Optimization of Language",
                "topic": "large language models",
                "abstract": "Retrieval-augmented generation (RAG) has shown great promise for knowledge-intensive tasks and recently advanced with agentic RAG, where language agents engage in multi-round interactions with external knowledge sources for adaptive information retrieval. However, existing agentic RAG methods often depend on ad-hoc prompt engineering and lack a unified optimization framework. We introduce RAG-Gym, a comprehensive platform that systematically explores three optimization dimensions: (1) prompt engineering, (2) actor tuning, and (3) critic training.",
                "introduction": "Large language models (LLMs) often struggle with knowledge-intensive questions when lacking sufficient or up-to-date domain knowledge, leading to inaccurate responses or hallucinations [97, 59, 28]. Retrieval-augmented generation (RAG) addresses this by grounding outputs in relevant information from information retrieval (IR) systems, improving both accuracy and verifiability of answers [42, 18].",
                "methodology": "To facilitate fine-grained process-level supervision and systematic evaluation of optimization methods for agentic RAG, we introduce the RAG-Gym framework. RAG-Gym formulates knowledge-intensive question answering as a high-level MDP with well-defined intermediate actions, and provides a modular approach for optimizing language agents across three key components.",
                "results": "Our comprehensive experiments across three widely used LLM post-training algorithms reveal that fine-grained, process-level supervision substantially boosts performance, particularly when both positive and negative feedback are integrated. Furthermore, we show that training a critic to evaluate intermediate steps yields additional gains across diverse LLMs.",
                "conclusion": "We introduce RAG-Gym, a systematic framework that enhances agentic RAG along three dimensions: prompt engineering, actor tuning, and critic training. Our optimized Re2Search++ agent achieves superior performance than existing methods on challenging knowledge-intensive tasks (+ 3.2%∼11.6% in average F1), especially on unseen datasets (+ 8.5%∼24.7%).",
                "claims": [
                    "Retrievalaugmented generation (RAG) has shown great promise for knowledgeintensive tasks.",
                    "Agentic RAG has recently advanced with language agents engaging in multiround interactions with external knowledge sources for adaptive information retrieval.",
                    "Existing agentic RAG methods often depend on adhoc prompt engineering.",
                    "Existing agentic RAG methods lack a unified optimization framework.",
                    "Finegrained, processlevel supervision substantially boosts performance.",
                    "Integrating both positive and negative feedback into finegrained, processlevel supervision yields additional gains.",
                    "Training a critic to evaluate intermediate steps yields additional gains across diverse LLMs.",
                    "The optimized Re2Search++ agent achieves superior performance than existing methods on challenging knowledgeintensive tasks.",
                    "The optimized Re2Search++ agent achieves superior performance on unseen datasets.",
                    "The optimized Re2Search++ agent outperforms existing methods by +3.2% to +11.6% in average F1.",
                    "The optimized Re2Search++ agent outperforms existing methods by +8.5% to +24.7% on unseen datasets."
                ],
                "methods": [],
                "datasets": [],
                "figures": [
                    {
                        "figure_id": "fig_1",
                        "caption": "2.1\nKnowledge-intensive Question Answering as Markov Decision Process\nWhile sequential token generation in LLMs can be modeled as an MDP [43, 49, 93], the integration\nof interactions with the IR environment introduces complex and inconsistent state transitions across\nagent architectures. To address this, we propose a hierarchical MDP formulation in RAG-Gym that\nunifies diverse agentic RAG designs. At the high level, agentic RAG is represented as a sequence of\nreasoning steps that interact with a",
                        "summary": "This figure represents a hierarchical Markov Decision Process (MDP) formulation for Knowledge-Intensive Question Answering, unifying diverse agent architectures."
                    },
                    {
                        "figure_id": "fig_2",
                        "caption": "illustrates the performance improvements achieved through critic training. The label \"With\nCritic\" indicates that an external critic evaluates 10 sampled actions at each step to select the best one.\nIn our experiments, all agents except for \"Direct\" consistently benefit from critic training. Moreover,\nthese performance gains transfer to actors using different LLMs. As shown in the figure, not only does\nthe original Llama-3.1-8B benefit from the trained critic, but both the DPO-tuned Llama-3.1-8B",
                        "summary": "The figure shows that critic training improves performance for most agents, including those using different large language models (LLMs)."
                    },
                    {
                        "figure_id": "fig_3",
                        "caption": ", show how the agent's performance scales with\nthe availability of more training data across four datasets. In general, the performance of Re2Search\nimproves with an increasing number of training samples, but the gains tend to converge as the sample\nsize grows. Notably, there is a sharp improvement in F1 scores on HotpotQA, 2WikiMultihopQA,\nand Bamboogle when comparing the ZSL baseline to process reward models trained on 250 samples,\nshowing that even a small amount of process reward data can yi",
                        "summary": "The figure shows how the performance of Re2Search improves with increasing training data, but gains tend to converge as sample size grows."
                    },
                    {
                        "figure_id": "fig_4",
                        "caption": "Performance of Re2Search agents with different numbers of actions sampled per step.\n5\nRelated Work\n5.1\nRetrieval-Augmented Generation\nRetrieval-Augmented Generation (RAG) has emerged as a powerful paradigm for enhancing large\nlanguage models (LLMs) on knowledge-intensive tasks. A typical RAG framework comprises two\ncore components: a retriever, which selects relevant documents from a large corpus, and a generator,\nwhich synthesizes information from these documents to produce coherent and context",
                        "summary": "This figure shows the performance of Re2Search agents with varying numbers of actions sampled per step."
                    },
                    {
                        "figure_id": "fig_5",
                        "caption": "Pipeline of the process data collection in RAG-Gym. Process reward data is collected by\nrandomly sampling action candidates at each time step and using an external annotator (e.g., GPT-4o)\nto select the best one. The episode is terminated when the agent generates a final answer.\nFor the implementation of the IR environment, we select Wikipedia as the supporting corpus for the\nretrieval of relevant information for questions from HotpotQA, 2WikiMultihopQA, and Bamboogle.\nFor the environment of sol",
                        "summary": "The figure illustrates the pipeline for collecting process data in RAG-Gym, involving sampling, annotation, and termination of episodes."
                    },
                    {
                        "figure_id": "fig_7",
                        "caption": ", given the question \"What was the father\nof the last surviving Canadian father of Confederation?\", the three agents show distinct behaviors\nwhen generating the first action.\nThe RAG agent directly passes the question as a search query without decomposition, relying entirely\non retrieval to infer the answer. This often leads to ineffective searches that fail to retrieve necessary\nintermediate facts. ReAct and Search-o1 improve upon this by engaging in stepwise query reasoning,\nfirst identifying ",
                        "summary": "This figure shows the distinct behaviors of three AI agents when generating the first action to answer a question about Canadian history."
                    },
                    {
                        "figure_id": "fig_8",
                        "caption": "Template used for history knowledge summarization in Search-o1 and Re2Search.\nPrompt template for generating actions using the Re2Search agent\nYou are a helpful assistant. Your task is to answer a given question following user instructions.'\n### Information-seeking History\n{{history}}\n### Original Question\n{{question}}\nYour output must include three sections:\n1. **### Step-by-step Reasoning**:\n- Think step-by-step and then answer the question.\n2. **### Unverified Claim Identification**:\n- Identi",
                        "summary": "This figure shows a template used for generating responses to user questions, including step-by-step reasoning and unverified claim identification."
                    },
                    {
                        "figure_id": "fig_10",
                        "caption": "Template used by GPT-4o to rank action candidates given the state.\n25",
                        "summary": "The figure shows a template used by GPT-4o to rank action candidates based on the current state, with a focus on the ranking process."
                    }
                ],
                "tables": [
                    {
                        "table_id": "table_1",
                        "caption": ") and introduce a novel agent design\nRe2Search that leverages reasoning reflection to improve performance. Our comprehensive experi-\nments across three widely used LLM post-training algorithms reveal that fine-grained, process-level\nsupervision substantially boosts performance, particularly when both positive and negative feedback\nare integrated. Furthermore, we show that training a critic to evaluate intermediate steps yields\nadditional gains across diverse LLMs. By integrating these insights, ",
                        "insight": "Fine-grained, process-level supervision, particularly with both positive and negative feedback, substantially boosts the performance of LLM post-training algorithms."
                    },
                    {
                        "table_id": "table_2",
                        "caption": "presents a performance comparison of various agents and their tuned versions using different\nactor tuning algorithms in RAG-Gym. The results indicate that the Re2Search agent consistently\noutperforms other agents in both zero-shot and actor-tuned settings. Furthermore, when comparing\nTable 2 with Table 1, which details the functional components of each agent, it can be observed\nthat more components generally leads to improved performance. This observation validates the\neffectiveness of the summa",
                        "insight": "The Re2Search agent consistently outperforms other agents in both zero-shot and actor-tuned settings."
                    },
                    {
                        "table_id": "table_3",
                        "caption": "Comparison of Re2Search++ and other methods.\nShading indicates in-domain model\nperformance. CEM represents the \"Cover Exact Match\" used in [69].\nLLM\nMethod\nHotpotQA\n2WikiMultihopQA\nBamboogle\nAverage\nEM\nCEM\nF1\nEM\nCEM\nF1\nEM\nCEM\nF1\nEM\nCEM\nF1\nLlama\n-3.1-8B\nReAct\n30.70\n38.40\n41.09\n28.90\n38.00\n35.03\n32.00\n36.80\n41.35\n30.57\n37.73\n39.16\nSearch-o1\n35.30\n43.80\n47.33\n34.00\n45.80\n41.29\n44.80\n48.80\n52.50\n38.03\n46.13\n47.04\nR1-Searcher\n44.90\n50.40\n56.88\n48.70\n51.30\n54.24\n38.40\n40.80\n53.21\n44.00\n47.50\n54.78\nRe2",
                        "insight": "Re2Search++ outperformed other methods in all tasks, achieving the highest average F1 scores across HotpotQA, 2WikiMultihopQA, and Bamboogle."
                    },
                    {
                        "table_id": "table_4",
                        "caption": "The reward model trained with GPT-4o annotations delivers the\nhighest performance across all datasets, effectively providing accurate, fine-grained process rewards\nfor agent optimization. Moreover, it exhibits the best alignment with human preferences, achieving\nan agreement rate of 85.85% with human annotators. In contrast, although rollouts and Llama-3.1-8B\nannotations improve action selection relative to a process reward model with random selections, they\nare generally less effective than GPT",
                        "insight": "The reward model trained with GPT-4o annotations achieves the highest performance and best alignment with human preferences."
                    },
                    {
                        "table_id": "table_6",
                        "caption": "). The model is tasked with identifying the mechanism of action of the most likely\nanti-diabetic medication for a 60-year-old patient presenting with symptoms indicative of fluid\noverload.\nFor the generation of the first action, the agent initially generates a broad and less actionable query\nabout heart failure, which, while relevant, does not directly contribute to identifying the correct\nmedication. Meanwhile, it also provides another candidate action with the query \"What are common\nclasses of",
                        "insight": "The model initially generates a broad query about heart failure, but also identifies a relevant medication class."
                    }
                ],
                "citations": [
                    ", the newly introduced reasoning reflection directs the agent to scrutinize its reasoning process",
                    ". Subsequent research has focused on improving both the retriever's ability to select relevant",
                    "Josh Achiam, Steven Adler, Sandhini Agarwal, Lama Ahmad, Ilge Akkaya, Florencia Leoni",
                    "Victor Akinwande, Yiding Jiang, Dylan Sam, and J Zico Kolter.",
                    "Chenxin An, Ming Zhong, Zhichao Geng, Jianqiang Yang, and Xipeng Qiu. Retrievalsum: A",
                    "Akari Asai, Zeqiu Wu, Yizhong Wang, Avirup Sil, and Hannaneh Hajishirzi. Self-rag: Learn-",
                    "Amanda Askell, Yuntao Bai, Anna Chen, Dawn Drain, Deep Ganguli, Tom Henighan, Andy",
                    "Yuntao Bai, Andy Jones, Kamal Ndousse, Amanda Askell, Anna Chen, Nova DasSarma, Dawn",
                    "Sebastian Borgeaud, Arthur Mensch, Jordan Hoffmann, Trevor Cai, Eliza Rutherford, Katie",
                    "Mingyang Chen, Tianpeng Li, Haoze Sun, Yijie Zhou, Chenzheng Zhu, Haofen Wang, Jeff Z",
                    "Mingyue Cheng, Yucong Luo, Jie Ouyang, Qi Liu, Huijie Liu, Li Li, Shuo Yu, Bohou Zhang,",
                    "Hyung Won Chung, Le Hou, Shayne Longpre, Barret Zoph, Yi Tay, William Fedus, Yunxuan",
                    "Gordon V Cormack, Charles LA Clarke, and Stefan Buettcher. Reciprocal rank fusion outper-",
                    "Guanting Dong, Chenghao Zhang, Mengjie Deng, Yutao Zhu, Zhicheng Dou, and Ji-Rong Wen.",
                    "Abhimanyu Dubey, Abhinav Jauhri, Abhinav Pandey, Abhishek Kadian, Ahmad Al-Dahle,",
                    "Kawin Ethayarajh, Winnie Xu, Niklas Muennighoff, Dan Jurafsky, and Douwe Kiela. Kto:",
                    "Feiteng Fang, Yuelin Bai, Shiwen Ni, Min Yang, Xiaojun Chen, and Ruifeng Xu. Enhancing",
                    "Jiayi Fu, Xuandong Zhao, Chengyuan Yao, Heng Wang, Qi Han, and Yanghua Xiao. Reward",
                    "Jingsheng Gao, Linxu Li, Weiyuan Li, Yuzhuo Fu, and Bin Dai. Smartrag: Jointly learn",
                    "Yunfan Gao, Yun Xiong, Xinyu Gao, Kangxiang Jia, Jinliu Pan, Yuxi Bi, Yi Dai, Jiawei Sun,",
                    "Daya Guo, Dejian Yang, Haowei Zhang, Junxiao Song, Ruoyu Zhang, Runxin Xu, Qihao Zhu,",
                    "Binglan Han, Teo Susnjak, and Anuradha Mathrani. Automating systematic literature reviews",
                    "Xanh Ho, Anh-Khoa Duong Nguyen, Saku Sugawara, and Akiko Aizawa. Constructing a",
                    "Sheryl Hsu, Omar Khattab, Chelsea Finn, and Archit Sharma. Grounding by trying: Llms with",
                    "Edward J Hu, Yelong Shen, Phillip Wallis, Zeyuan Allen-Zhu, Yuanzhi Li, Shean Wang,",
                    "Jian Hu, Xibin Wu, Zilin Zhu, Weixun Wang, Dehao Zhang, Yu Cao, et al. Openrlhf: An",
                    "Gautier Izacard and Édouard Grave. Leveraging passage retrieval with generative models for",
                    "Gautier Izacard, Patrick Lewis, Maria Lomeli, Lucas Hosseini, Fabio Petroni, Timo Schick, Jane",
                    "Soyeong Jeong, Jinheon Baek, Sukmin Cho, Sung Ju Hwang, and Jong-Cheol Park. Adaptive-",
                    "Ziwei Ji, Nayeon Lee, Rita Frieske, Tiezheng Yu, Dan Su, Yan Xu, Etsuko Ishii, Ye Jin Bang,",
                    "Pengcheng Jiang, Lang Cao, Ruike Zhu, Minhao Jiang, Yunyi Zhang, Jimeng Sun, and Jiawei",
                    "Pengcheng Jiang, Jiacheng Lin, Lang Cao, Runchu Tian, SeongKu Kang, Zifeng Wang, Jimeng",
                    "Zhengbao Jiang, Frank F Xu, Luyu Gao, Zhiqing Sun, Qian Liu, Jane Dwivedi-Yu, Yiming Yang,",
                    "Ziyan Jiang, Xueguang Ma, and Wenhu Chen. Longrag: Enhancing retrieval-augmented",
                    "Bowen Jin, Hansi Zeng, Zhenrui Yue, Jinsung Yoon, Sercan Arik, Dong Wang, Hamed Za-",
                    "Di Jin, Eileen Pan, Nassim Oufattole, Wei-Hung Weng, Hanyi Fang, and Peter Szolovits. What",
                    "Qiao Jin, Won Kim, Qingyu Chen, Donald C Comeau, Lana Yeganova, W John Wilbur, and",
                    "Zhuoran Jin, Hongbang Yuan, Tianyi Men, Pengfei Cao, Yubo Chen, Kang Liu, and Jun",
                    "Vladimir Karpukhin, Barlas Oguz, Sewon Min, Patrick Lewis, Ledell Wu, Sergey Edunov,",
                    "Tushar Khot, Harsh Trivedi, Matthew Finlayson, Yao Fu, Kyle Richardson, Peter Clark, and",
                    "Jakub Lála, Odhran O'Donoghue, Aleksandar Shtedritski, Sam Cox, Samuel G Rodriques, and",
                    "Divya Lamba. The role of prompt engineering in improving language understanding and",
                    "Guido Lang and Tan Gürpinar. Ai-powered learning support: A study of retrieval-augmented",
                    "Patrick Lewis, Ethan Perez, Aleksandra Piktus, Fabio Petroni, Vladimir Karpukhin, Naman",
                    "Dongheng Li, Yongchang Hao, and Lili Mou. Llmr: Knowledge distillation with a large",
                    "Xiaoxi Li, Guanting Dong, Jiajie Jin, Yuyao Zhang, Yujia Zhou, Yutao Zhu, Peitian Zhang, and",
                    "Xingxuan Li, Weiwen Xu, Ruochen Zhao, Fangkai Jiao, Shafiq Joty, and Lidong Bing. Can we",
                    "Hunter Lightman, Vineet Kosaraju, Yuri Burda, Harrison Edwards, Bowen Baker, Teddy",
                    "Fei Liu et al. Learning to summarize from human feedback. In Proceedings of the 58th Annual",
                    "Siru Liu, Allison B McCoy, and Adam Wright. Improving large language model applications",
                    "Hao Ma, Tianyi Hu, Zhiqiang Pu, Liu Boyin, Xiaolin Ai, Yanyan Liang, and Min Chen. Coevolv-",
                    "Yu Meng, Mengzhou Xia, and Danqi Chen. Simpo: Simple preference optimization with a",
                    "Thang Nguyen, Peter Chin, and Yu-Wing Tai. Reward-rag: Enhancing rag with reward driven",
                    "Long Ouyang, Jeffrey Wu, Xu Jiang, Diogo Almeida, Carroll Wainwright, Pamela Mishkin,",
                    "Nicholas Pipitone and Ghita Houir Alami.",
                    "Ofir Press, Muru Zhang, Sewon Min, Ludwig Schmidt, Noah A Smith, and Mike Lewis.",
                    "Cheng Qian, Emre Can Acikgoz, Qi He, Hongru Wang, Xiusi Chen, Dilek Hakkani-Tür, Gokhan",
                    "Rafael Rafailov, Archit Sharma, Eric Mitchell, Christopher D Manning, Stefano Ermon, and",
                    "Ori Ram, Yoav Levine, Itay Dalmedigos, Dor Muhlgay, Amnon Shashua, Kevin Leyton-Brown,",
                    "Stephen Robertson, Hugo Zaragoza, et al. The probabilistic relevance framework: Bm25 and",
                    "Satya S Sahoo, Joseph M Plasek, Hua Xu, Özlem Uzuner, Trevor Cohen, Meliha Yetisgen,",
                    "John Schulman, Filip Wolski, Prafulla Dhariwal, Alec Radford, and Oleg Klimov. Proximal",
                    "Zhihong Shao, Yeyun Gong, Yelong Shen, Minlie Huang, Nan Duan, and Weizhu Chen.",
                    "Zhihong Shao, Peiyi Wang, Qihao Zhu, Runxin Xu, Junxiao Song, Xiao Bi, Haowei Zhang,",
                    "Yucheng Shi, Tianze Yang, Canyu Chen, Quanzheng Li, Tianming Liu, Xiang Li, and Ninghao",
                    "Zhengliang Shi, Shuo Zhang, Weiwei Sun, Shen Gao, Pengjie Ren, Zhumin Chen, and Zhaochun",
                    "Noah Shinn, Federico Cassano, Ashwin Gopinath, Karthik Narasimhan, and Shunyu Yao.",
                    "Kurt Shuster, Spencer Poff, Moya Chen, Douwe Kiela, and Jason Weston. Retrieval augmenta-",
                    "Joar Skalse, Nikolaus Howe, Dmitrii Krasheninnikov, and David Krueger.",
                    "Michael D Skarlinski, Sam Cox, Jon M Laurent, James D Braza, Michaela Hinks, Michael J",
                    "Huatong Song, Jinhao Jiang, Yingqian Min, Jie Chen, Zhipeng Chen, Wayne Xin Zhao, Lei Fang,",
                    "Hari Subramonyam, Divy Thakkar, Andrew Ku, Juergen Dieber, and Anoop K Sinha. Prototyp-",
                    "Zhongxiang Sun, Qipeng Wang, Weijie Yu, Xiaoxue Zang, Kai Zheng, Jun Xu, Xiao Zhang,",
                    "Jakub Swacha and Michał Gracel. Retrieval-augmented generation (rag) chatbots for education:",
                    "Harsh Trivedi, Niranjan Balasubramanian, Tushar Khot, and Ashish Sabharwal. Interleaving",
                    "Ashish Vaswani, Noam Shazeer, Niki Parmar, Jakob Uszkoreit, Llion Jones, Aidan N Gomez,",
                    "Leandro von Werra, Younes Belkada, Lewis Tunstall, Edward Beeching, Tristan Thrush, Nathan",
                    "Keheng Wang, Feiyu Duan, Sirui Wang, Peiguang Li, Yunsen Xian, Chuantao Yin, Wenge",
                    "Peiyi Wang, Lei Li, Zhihong Shao, Runxin Xu, Damai Dai, Yifei Li, Deli Chen, Yu Wu, and",
                    "Yuxia Wang, Minghan Wang, Muhammad Arslan Manzoor, Fei Liu, Georgi Georgiev, Rocktim",
                    "Zihao Wang, Anji Liu, Haowei Lin, Jiaqi Li, Xiaojian Ma, and Yitao Liang. Rat: Retrieval",
                    "Zilong Wang, Zifeng Wang, Long Le, Huaixiu Steven Zheng, Swaroop Mishra, Vincent Perot,",
                    "Jason Wei, Xuezhi Wang, Dale Schuurmans, Maarten Bosma, Fei Xia, Ed Chi, Quoc V Le,",
                    "Zhepei Wei, Wei-Lin Chen, and Yu Meng. InstructRAG: Instructing retrieval-augmented",
                    "Nirmalie Wiratunga, Ramitha Abeyratne, Lasal Jayawardena, Kyle Martin, Stewart Massie,",
                    "Shitao Xiao, Zheng Liu, Peitian Zhang, and Niklas Muennighoff. C-pack: Packaged resources",
                    "Guangzhi Xiong, Qiao Jin, Zhiyong Lu, and Aidong Zhang. Benchmarking retrieval-augmented",
                    "Guangzhi Xiong, Qiao Jin, Xiao Wang, Minjia Zhang, Zhiyong Lu, and Aidong Zhang. Im-",
                    "Haoran Xu, Amr Sharaf, Yunmo Chen, Weiting Tan, Lingfeng Shen, Benjamin Van Durme, Ken-",
                    "Ran Xu, Hui Liu, Sreyashi Nag, Zhenwei Dai, Yaochen Xie, Xianfeng Tang, Chen Luo, Yang",
                    "Ran Xu, Wenqi Shi, Yue Yu, Yuchen Zhuang, Yanqiao Zhu, May Dongmei Wang, Joyce C.",
                    "Zhilin Yang, Peng Qi, Saizheng Zhang, Yoshua Bengio, William Cohen, Ruslan Salakhutdinov,",
                    "Shunyu Yao, Jeffrey Zhao, Dian Yu, Nan Du, Izhak Shafran, Karthik Narasimhan, and Yuan",
                    "Tian Yu, Shaolei Zhang, and Yang Feng. Auto-rag: Autonomous retrieval-augmented generation",
                    "Oussama Zekri, Ambroise Odonnat, Abdelhakim Benechehab, Linus Bleistein, Nicolas Boullé,",
                    "Hanning Zhang, Juntong Song, Juno Zhu, Yuanhao Wu, Tong Zhang, and Cheng Niu. Rag-",
                    "Peitian Zhang, Shitao Xiao, Zheng Liu, Zhicheng Dou, and Jian-Yun Nie. Retrieve anything to",
                    "Tianjun Zhang, Shishir G Patil, Naman Jain, Sheng Shen, Matei Zaharia, Ion Stoica, and",
                    "Yue Zhang, Yafu Li, Leyang Cui, Deng Cai, Lemao Liu, Tingchen Fu, Xinting Huang, Enbo",
                    "Zhenru Zhang, Chujie Zheng, Yangzhen Wu, Beichen Zhang, Runji Lin, Bowen Yu, Dayiheng"
                ]
            },
            {
                "conversation_id": "5dc4b645-9abc-4e4a-85c4-97436da5ccee",
                "paper_id": "paper_3602352dd7adfcef",
                "title": "Retrieval Augmented Generation (RAG) for",
                "topic": "specialized natural language processing",
                "abstract": "Retrieval Augmented Generation (RAG) systems of-ten face limitations in specialized domains such as fintech, where domain-specific ontologies, dense terminology, and acronyms complicate effective retrieval and synthesis. This paper introduces an agentic RAG architecture designed to address these challenges through a modular pipeline of specialised agents.",
                "introduction": "Retrieval Augmented Generation (RAG) combines large language models (LLMs) with external document retrieval, allowing models to access information beyond their training data. However, deploying such systems at scale in highly specialized and tightly regulated domains such as financial technology is far from straightforward.",
                "methodology": "We propose a hierarchical agent framework, where an Orchestrator Agent delegates tasks to specialized sub-agents responsible for acronym resolution, domain-aware query rewriting, and cross-encoder-based re-ranking. This modular structure allows the system to encode organizational idiosyncrasies such as internal taxonomies, access controls, and documentation practices.",
                "results": "Experimental results demonstrate that the agentic RAG system outperforms the baseline in retrieval precision and relevance, albeit with increased latency. These findings suggest that structured, multi-agent methodologies offer a promising direction for enhancing retrieval robustness in complex, domain-specific settings.",
                "conclusion": "Our primary contributions include: A Fintech-focused Agentic Design: We develop an Orchestrator Agent that coordinates specialized agents for acronym resolution, iterative sub-query generation using key phrases, and context refinement through a cross-encoder re-ranking method.",
                "claims": [
                    "Retrieval Augmented Generation (RAG) systems often face limitations in specialized domains such as fintech.",
                    "The agentic RAG architecture addresses the challenges in fintech through a modular pipeline of specialized agents.",
                    "The agentic RAG system outperforms the baseline in retrieval precision and relevance.",
                    "The agentic RAG system has increased latency compared to the baseline.",
                    "Structured, multiagent methodologies offer a promising direction for enhancing retrieval robustness in complex, domainspecific settings.",
                    "We develop an Orchestrator Agent that coordinates specialized agents for acronym resolution.",
                    "We develop an Orchestrator Agent that coordinates specialized agents for iterative subquery generation using key phrases.",
                    "We develop an Orchestrator Agent that coordinates specialized agents for context refinement through a crossencoder reranking method."
                ],
                "methods": [],
                "datasets": [],
                "figures": [
                    {
                        "figure_id": "fig_1",
                        "caption": "Word cloud illustrating the distribution of internal knowledge artifacts\nin fintech. The prominence of terms such as \"feature,\" \"status,\" \"model,\" and\n\"API\" reflects the operational focus of internal documentation-often centered\naround technical specifications, product state, and integration interfaces. This\nconcentration of tightly scoped, semi-structured information highlights the\nchallenge of designing RAG systems that can interpret fragmented context\nacross teams and tools, where standard Sa",
                        "summary": "The figure shows a word cloud of internal knowledge artifacts in fintech, highlighting a focus on technical specifications and product state."
                    },
                    {
                        "figure_id": "fig_2",
                        "caption": "The B-RAG system, illustrated in Figure 2, consists of a\nsequence of specialized agents structured to enable stepwise\ninformation retrieval and synthesis. The process begins with\nthe user's initial input, which serves as the contextual founda-\ntion for subsequent components. This input is then propagated\nthrough the following agents:\n(a) Query Reformulator Agent: Takes the user's question\nand refines it into a concise, keyword-focused query\noptimized for retrieval. It uses predefined prompt tem-",
                        "summary": "The figure illustrates the B-RAG system, a sequence of agents that enables stepwise information retrieval and synthesis from user input."
                    },
                    {
                        "figure_id": "fig_3",
                        "caption": "It highlights the differences\nin processing flow and iterative mechanisms.\nC. System Architecture and Workflow\nThe A-RAG system comprises a set of lightweight, modular\nagents orchestrated to support iterative retrieval and reasoning.\nThe following subsections describe the system's core agent\ncomponents and the operational workflow using a representa-\ntive fintech query example.\nCore Agent Components: The orchestrator coordinates eight\nspecialized agents, each responsible for a distinct stage in ",
                        "summary": "The figure illustrates the architecture and workflow of the A-RAG system, comprising eight specialized agents orchestrated by an orchestrator."
                    },
                    {
                        "figure_id": "fig_4",
                        "caption": "shows\nthe distribution of chunk lengths measured by word count.\nFig. 4. Distribution of chunk lengths by word count. The majority of chunks\nare between 50 and 120 words, showing the trade-off between retrieval\ngranularity and contextual coherence.\nTo further illustrate the dataset composition, Figure 1 and\nFigure 5 provide complementary views of term frequency.\nBoth highlight the prevalence of domain-specific language in\nthe internal fintech corpus, particularly terms such as \"fea-\nture,\" \"API,\"",
                        "summary": "The figure shows the distribution of chunk lengths, with most chunks ranging from 50 to 120 words, indicating a balance between retrieval granularity and contextual coherence."
                    },
                    {
                        "figure_id": "fig_6",
                        "caption": ", A-RAG notably reduces the fre-\nquency of low-quality answers (s<5) and increases the pro-\nportion of responses in the top rubric tier (s ≥9). The per-\nquestion score deltas (Figure 7) show that A-RAG is preferred\nin 64 % of cases, ties in 25 % and is outperformed by B-RAG\nin only 11 %. Even in those rare cases, the largest drop is\njust 3 points, indicating that A-RAG rarely degrades answer\nquality.\nFig. 6.\nHistogram+KDE of all 85 LLM-judge scores per pipeline. A-RAG\nshifts mass into the 7-10 b",
                        "summary": "This figure shows a histogram of LLM-judge scores, demonstrating that A-RAG shifts mass into the top rubric tier (7-10) compared to the baseline."
                    }
                ],
                "tables": [],
                "citations": [
                    "V. Scotti and M. J. Carman, \"Llm support for real-time technical",
                    "Cursor AI, \"Cursor: The ai-first code editor,\" https://www.cursor.so,",
                    "OpenAI, \"Chatgpt: Optimizing language models for dialogue,\" https:",
                    "E. Schuman, \"88% of AI pilots fail to reach production - but that's",
                    "A. Menshawy, Z. Nawaz, and M. Fahmy, \"Navigating challenges and",
                    "P. Giudici, \"Fintech risk management: A research challenge for artificial",
                    "Mastercard, \"Mdes for merchants (m4m): Mastercard digital enablement",
                    "--, \"Switchcore: Mastercard transaction switching platform,\" https:",
                    "Y. Liu, D. Iter, Y. Xu, S. Wang, R. Xu, and C. Zhu, \"G-eval: Nlg",
                    "J. Chen, H. Lin, X. Han, and L. Sun, \"Benchmarking large language",
                    "A. Singh, A. Ehtesham, S. Kumar, and T. T. Khoei, \"Agentic retrieval-",
                    "T. Nguyen, P. Chin, and Y.-W. Tai, \"Ma-rag: Multi-agent retrieval-",
                    "Pathway Community, \"Adaptive agents for real-time rag: Domain-",
                    "R. C. Barron, V. Grantcharov, S. Wanna, M. E. Eren, M. Bhattarai,",
                    "H. Daiya, \"Leveraging large language models (llms) for enhanced risk",
                    "M. Broughton, \"Large language models: How they help fintechs,\" https:",
                    "Lumenova AI, \"Ai in finance: The promise and risks of rag,\" https:",
                    "P. H. Leal, \"Building a financial education chatbot with retrieval-"
                ]
            }
        ]
    }
} as const;

export type MockApiResponse = typeof mockApiResponse;
