// Comprehensive mock data for the Research Literature Agent

import {
  Paper,
  Agent,
  Message,
  TimelineEvent,
  GraphNode,
  Verdict,
  Stage,
} from './types';
import { STAGE_COLORS } from './colors';

export const mockPapers: Paper[] = [
  {
    id: '1',
    title: 'Attention Is All You Need',
    authors: ['Vaswani, A.', 'Shazeer, N.', 'Parmar, N.'],
    year: 2017,
    source: 'arXiv',
    abstract:
      'The dominant sequence transduction models are based on complex recurrent or convolutional neural networks in an encoder-decoder configuration. The best performing models also connect the encoder and decoder through an attention mechanism.',
    methodology: 'Transformer architecture with self-attention mechanisms',
    results: 'Achieved BLEU scores of 28.4 on WMT 2014 English-to-German translation',
    limitations: 'Computational cost, training time requirements',
  },
  {
    id: '2',
    title: 'Language Models are Unsupervised Multitask Learners',
    authors: ['Radford, A.', 'Wu, J.', 'Child, R.'],
    year: 2019,
    source: 'OpenAI',
    abstract:
      'Natural language processing tasks are typically approached with task-specific architectures and training procedures. We demonstrate that language models begin to learn these tasks without any explicit supervision when trained on a new dataset of Internet text.',
    methodology: 'Scaled language model training on diverse text corpus',
    results: 'Demonstrated zero-shot task transfer capabilities',
    limitations: 'Bias in training data, ethical concerns with scale',
  },
  {
    id: '3',
    title: 'BERT: Pre-training of Deep Bidirectional Transformers',
    authors: ['Devlin, J.', 'Chang, M.', 'Lee, K.'],
    year: 2018,
    source: 'Google',
    abstract:
      'We introduce BERT, a new method of pre-training language representations that obtains state-of-the-art results on a wide array of Natural Language Processing tasks.',
    methodology: 'Bidirectional transformer pre-training with MLM and NSP tasks',
    results: 'Surpassed previous SOTA on 11 NLP tasks',
    limitations: 'Large model size, computational requirements',
  },
  {
    id: '4',
    title: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks',
    authors: ['Lewis, P.', 'Perez, E.', 'Piktus, A.'],
    year: 2020,
    source: 'arXiv',
    abstract:
      'Large pre-trained language models have been shown to store factual knowledge in their parameters, but accessing and manipulating this knowledge is still challenging. We propose RAG, which combines the strengths of parametric and non-parametric memory.',
    methodology: 'Dense passage retriever + sequence-to-sequence generator',
    results: '7.46 F1 on Natural Questions, outperforming dense retrievers',
    limitations: 'Retrieval latency, indexing overhead',
  },
  {
    id: '5',
    title: 'The Illustrated Transformer',
    authors: ['Alammar, J.'],
    year: 2018,
    source: 'Blog Post',
    abstract: 'A visual guide to understanding transformer architecture and mechanisms.',
    methodology: 'Educational visualization of attention mechanisms',
    results: 'Widespread adoption in AI education',
    limitations: 'Simplified representation, pedagogical only',
  },
  {
    id: '6',
    title: 'Exploring the Limits of Transfer Learning',
    authors: ['Raffel, C.', 'Shazeer, N.', 'Roberts, A.'],
    year: 2019,
    source: 'arXiv',
    abstract:
      'Transfer learning has become a key to building state-of-the-art natural language processing systems. We present the T5 model and a unified text-to-text framework.',
    methodology: 'Unified text-to-text transfer transformer',
    results: 'State-of-the-art on GLUE, SuperGLUE, and SQuAD benchmarks',
    limitations: 'Model scale and computational requirements',
  },
  {
    id: '7',
    title: 'Language Models as Knowledge Bases?',
    authors: ['Petroni, F.', 'Rocktäschel, T.', 'Lewis, P.'],
    year: 2019,
    source: 'arXiv',
    abstract:
      'Recent progress in pretraining language models on large text corpora has resulted in a rush to apply these models to many downstream tasks. We investigate whether language models can serve as knowledge bases.',
    methodology: 'Probing tasks on pre-trained models',
    results: 'Identified knowledge retention in model parameters',
    limitations: 'Limited to factual knowledge, factuality concerns',
  },
  {
    id: '8',
    title: 'Scaling Laws for Neural Language Models',
    authors: ['Kaplan, J.', 'McCandlish, S.', 'Henighan, T.'],
    year: 2020,
    source: 'OpenAI',
    abstract:
      'We study the performance of language models as a function of model size, dataset size, and the amount of compute used for training. We propose power-law relationships and scaling laws.',
    methodology: 'Systematic experiments on model scaling',
    results: 'Identified consistent power-law relationships',
    limitations: 'Specific to language modeling, compute intensive',
  },
  {
    id: '9',
    title: 'Federated Learning of N-gram Language Models',
    authors: ['Bonawitz, K.', 'Eichner, H.', 'Grieskamp, W.'],
    year: 2019,
    source: 'Google',
    abstract:
      'We present experiments with learning models in a federated setting where data is distributed over mobile devices and not sent to a central server.',
    methodology: 'Federated learning with language models',
    results: 'Successfully trained models on distributed devices',
    limitations: 'Communication overhead, privacy-accuracy tradeoffs',
  },
  {
    id: '10',
    title: 'Dense Passage Retrieval for Open-Domain Question Answering',
    authors: ['Karpukhin, V.', 'Oöz, B.', 'Edunov, S.'],
    year: 2020,
    source: 'arXiv',
    abstract:
      'Open-domain question answering relies on efficient passage retrieval to find relevant documents. We investigate whether dense retrieval can outperform sparse retrieval methods.',
    methodology: 'Dual-encoder architecture with dense embeddings',
    results: 'Outperformed BM25 on SQuAD and Natural Questions',
    limitations: 'Scalability challenges, indexing requirements',
  },
  {
    id: '11',
    title: 'Few-shot Learning with Graph Neural Networks',
    authors: ['Garcia, V.', 'Bruna, J.'],
    year: 2018,
    source: 'arXiv',
    abstract:
      'We explore the use of graph neural networks for few-shot learning, leveraging the structure of the problem to improve sample efficiency.',
    methodology: 'Graph-based meta-learning approach',
    results: 'Improved few-shot classification accuracy',
    limitations: 'Graph construction complexity',
  },
  {
    id: '12',
    title: 'Knowledge Graph Embedding via Dynamic Mapping Matrix',
    authors: ['Zhang, F.', 'Yuan, N.', 'Lian, D.'],
    year: 2018,
    source: 'arXiv',
    abstract:
      'Knowledge graphs have become increasingly important for supporting knowledge applications. We propose a method for embedding knowledge graphs using dynamic mapping.',
    methodology: 'Translation-based embedding with dynamic matrices',
    results: 'Improved link prediction on benchmark datasets',
    limitations: 'Scalability to very large graphs',
  },
];

export const mockAgents: Agent[] = [
  {
    id: '1',
    name: 'Literature Analyst',
    role: 'Surveys and synthesizes papers',
    color: '#FF6F00',
    analysis:
      'Found 12 highly relevant papers on transformer architectures and pre-training methods. All papers cited between 2017-2020 with strong publication venues.',
    status: 'complete',
    icon: '📚',
  },
  {
    id: '2',
    name: 'Method Architect',
    role: 'Identifies methodologies and frameworks',
    color: '#FF6F00',
    analysis:
      'Primary methodologies: Attention mechanisms, self-supervised learning, and transfer learning. Common framework: Pre-training then fine-tuning paradigm.',
    status: 'complete',
    icon: '🏗️',
  },
  {
    id: '3',
    name: 'Results Analyst',
    role: 'Evaluates findings and metrics',
    color: '#FF6F00',
    analysis:
      'Benchmarks used: GLUE, SQuAD, WMT14. Performance improvements across tasks: 2-7 BLEU points for translation, 8-15 F1 on QA tasks.',
    status: 'complete',
    icon: '📊',
  },
  {
    id: '4',
    name: 'Limitations Reviewer',
    role: 'Identifies gaps and constraints',
    color: '#FF6F00',
    analysis:
      'Key limitations: Computational cost, data bias, factuality concerns. Common theme: Scalability and interpretability remain open challenges.',
    status: 'complete',
    icon: '⚠️',
  },
];

export const mockVeridict: Verdict = {
  summary:
    'The research literature demonstrates a clear evolution in NLP architectures from RNNs to transformer-based models, with significant improvements in performance across benchmarks. Pre-training on large unlabeled corpora followed by task-specific fine-tuning has become the standard paradigm.',
  keyFindings: [
    'Attention mechanisms are crucial for sequence modeling performance',
    'Bidirectional context improves downstream task performance',
    'Transfer learning enables strong few-shot and zero-shot capabilities',
    'Scaling follows consistent power laws with model size and data size',
  ],
  contradictions: [
    'Dense vs sparse retrieval: Initial belief that BM25 would always win was disproven',
    'Model size vs efficiency: Larger models not always better; depends on task and available compute',
  ],
  gaps: [
    'Limited understanding of how knowledge is stored in model parameters',
    'Factuality and hallucination problems in large language models',
    'Interpretability of attention mechanisms remains unclear',
    'Energy efficiency and carbon footprint concerns underexplored',
  ],
  recommendations: [
    'Future work should focus on interpretability and robustness',
    'Explore more efficient architectures without sacrificing performance',
    'Investigate knowledge grounding and factuality verification',
    'Study federated and privacy-preserving training approaches',
  ],
};

export const mockRAGMessages: Message[] = [
  {
    id: '1',
    role: 'user',
    content: 'What are the main architectural innovations in the retrieved papers?',
    citations: [],
    timestamp: new Date(Date.now() - 180000),
  },
  {
    id: '2',
    role: 'assistant',
    content:
      'The retrieved papers highlight two major architectural innovations: (1) Self-attention mechanisms that allow models to focus on relevant tokens regardless of distance, and (2) Bidirectional context processing enabling models to understand both left and right context simultaneously.',
    citations: ['1', '3'],
    timestamp: new Date(Date.now() - 120000),
  },
  {
    id: '3',
    role: 'user',
    content: 'How do these papers compare in terms of model size and computational requirements?',
    citations: [],
    timestamp: new Date(Date.now() - 60000),
  },
  {
    id: '4',
    role: 'assistant',
    content:
      'The papers show a clear trend toward larger models with more parameters. BERT-Large uses 340M parameters, while later models exceed 1B parameters. Scaling laws suggest performance improves logarithmically with compute, but practical training requirements grow exponentially.',
    citations: ['6', '8'],
    timestamp: new Date(Date.now() - 30000),
  },
];

export const mockExecutionEvents: TimelineEvent[] = [
  {
    id: '1',
    timestamp: 0,
    title: 'Research query received',
    stage: 'crawler',
    details: 'Processing: "transformer architectures and pre-training methods"',
    status: 'complete',
  },
  {
    id: '2',
    timestamp: 1500,
    title: 'Search initiated',
    stage: 'crawler',
    details: 'Querying academic databases for relevant papers',
    status: 'complete',
  },
  {
    id: '3',
    timestamp: 3000,
    title: '12 papers discovered',
    stage: 'crawler',
    details: 'Found papers from arXiv, Google, and OpenAI',
    status: 'complete',
  },
  {
    id: '4',
    timestamp: 5000,
    title: 'NLP pipeline started',
    stage: 'nlp',
    details: 'Extracting abstracts, methods, and results',
    status: 'complete',
  },
  {
    id: '5',
    timestamp: 7000,
    title: 'Section extraction complete',
    stage: 'nlp',
    details: 'Extracted 48 sections across methodology, results, limitations',
    status: 'complete',
  },
  {
    id: '6',
    timestamp: 9000,
    title: 'Agent council assembled',
    stage: 'agents',
    details: 'Deploying 4 specialist agents for analysis',
    status: 'complete',
  },
  {
    id: '7',
    timestamp: 11000,
    title: 'Literature analyst report',
    stage: 'agents',
    details: 'Synthesized paper themes and chronology',
    status: 'complete',
  },
  {
    id: '8',
    timestamp: 13000,
    title: 'Method architect report',
    stage: 'agents',
    details: 'Identified common methodologies and frameworks',
    status: 'complete',
  },
  {
    id: '9',
    timestamp: 15000,
    title: 'Results analyst report',
    stage: 'agents',
    details: 'Evaluated metrics and benchmarks',
    status: 'complete',
  },
  {
    id: '10',
    timestamp: 17000,
    title: 'Limitations reviewer report',
    stage: 'agents',
    details: 'Documented constraints and open challenges',
    status: 'complete',
  },
  {
    id: '11',
    timestamp: 19000,
    title: 'Knowledge graph construction',
    stage: 'graph',
    details: 'Building entity and relationship graph from papers',
    status: 'complete',
  },
  {
    id: '12',
    timestamp: 21000,
    title: '15 nodes and 28 edges created',
    stage: 'graph',
    details: 'Concepts, techniques, and papers connected',
    status: 'complete',
  },
  {
    id: '13',
    timestamp: 23000,
    title: 'RAG indexing started',
    stage: 'rag',
    details: 'Computing embeddings for 48 text chunks',
    status: 'complete',
  },
  {
    id: '14',
    timestamp: 25000,
    title: 'Vector database populated',
    stage: 'rag',
    details: 'Ready for similarity search and retrieval',
    status: 'complete',
  },
  {
    id: '15',
    timestamp: 27000,
    title: 'Report generation started',
    stage: 'report',
    details: 'Compiling executive summary and sections',
    status: 'complete',
  },
  {
    id: '16',
    timestamp: 29000,
    title: 'Report sections compiled',
    stage: 'report',
    details: '6 sections: Summary, Papers, Methods, Contradictions, Gaps, Recommendations',
    status: 'complete',
  },
  {
    id: '17',
    timestamp: 31000,
    title: 'All stages complete',
    stage: 'trail',
    details: 'Research analysis workflow finished',
    status: 'complete',
  },
];

export const mockGraphNodes: GraphNode[] = [
  {
    id: 'transformer',
    label: 'Transformer',
    category: 'Architecture',
    connections: ['attention', 'bert', 'gpt', 'nlp'],
    description: 'Foundation architecture with self-attention mechanism',
  },
  {
    id: 'attention',
    label: 'Self-Attention',
    category: 'Mechanism',
    connections: ['transformer', 'bert', 'gpt'],
    description: 'Allows model to focus on relevant tokens',
  },
  {
    id: 'bert',
    label: 'BERT',
    category: 'Model',
    connections: ['transformer', 'attention', 'pretraining', 'downstream'],
    description: 'Bidirectional Encoder Representations from Transformers',
  },
  {
    id: 'gpt',
    label: 'GPT',
    category: 'Model',
    connections: ['transformer', 'attention', 'pretraining', 'zeroshot'],
    description: 'Generative Pre-trained Transformer',
  },
  {
    id: 'pretraining',
    label: 'Pre-training',
    category: 'Technique',
    connections: ['bert', 'gpt', 'downstream', 'transfer'],
    description: 'Training on large unlabeled corpora',
  },
  {
    id: 'downstream',
    label: 'Fine-tuning',
    category: 'Technique',
    connections: ['bert', 'pretraining', 'transfer', 'taskspec'],
    description: 'Adapting to specific downstream tasks',
  },
  {
    id: 'transfer',
    label: 'Transfer Learning',
    category: 'Paradigm',
    connections: ['pretraining', 'downstream', 'zeroshot'],
    description: 'Leveraging knowledge across tasks',
  },
  {
    id: 'zeroshot',
    label: 'Zero-shot',
    category: 'Capability',
    connections: ['gpt', 'transfer'],
    description: 'Task performance without task-specific training',
  },
  {
    id: 'retrieval',
    label: 'Retrieval',
    category: 'Technique',
    connections: ['rag', 'qa', 'dense'],
    description: 'Finding relevant documents or passages',
  },
  {
    id: 'rag',
    label: 'RAG',
    category: 'System',
    connections: ['retrieval', 'generation', 'qa', 'dense'],
    description: 'Retrieval-Augmented Generation system',
  },
  {
    id: 'generation',
    label: 'Generation',
    category: 'Technique',
    connections: ['rag', 'transformer'],
    description: 'Generating text from retrieved knowledge',
  },
  {
    id: 'qa',
    label: 'Question Answering',
    category: 'Task',
    connections: ['retrieval', 'rag', 'downstream'],
    description: 'Answering questions based on context',
  },
  {
    id: 'dense',
    label: 'Dense Retrieval',
    category: 'Technique',
    connections: ['retrieval', 'rag', 'embeddings'],
    description: 'Using neural embeddings for retrieval',
  },
  {
    id: 'embeddings',
    label: 'Embeddings',
    category: 'Representation',
    connections: ['dense', 'transformer'],
    description: 'Vector representations of text',
  },
  {
    id: 'nlp',
    label: 'NLP',
    category: 'Field',
    connections: ['transformer', 'downstream', 'qa'],
    description: 'Natural Language Processing',
  },
];

export const mockStages: Stage[] = [
  {
    id: 'crawler',
    name: 'Crawler',
    color: '#2196F3',
    status: 'complete',
    icon: '🔍',
    description: 'Search and retrieve academic papers',
  },
  {
    id: 'nlp',
    name: 'NLP Processor',
    color: '#9C27B0',
    status: 'complete',
    icon: '🧠',
    description: 'Extract sections and structure content',
  },
  {
    id: 'agents',
    name: 'Agent Council',
    color: '#FF6F00',
    status: 'complete',
    icon: '👥',
    description: 'Specialist agents analyze papers',
  },
  {
    id: 'graph',
    name: 'Knowledge Graph',
    color: '#00897B',
    status: 'complete',
    icon: '🕸️',
    description: 'Build entity relationships',
  },
  {
    id: 'rag',
    name: 'RAG Interface',
    color: '#E53935',
    status: 'complete',
    icon: '💬',
    description: 'Query with retrieved context',
  },
  {
    id: 'report',
    name: 'Final Report',
    color: '#43A047',
    status: 'complete',
    icon: '📄',
    description: 'Generate comprehensive findings',
  },
  {
    id: 'trail',
    name: 'Execution Trail',
    color: '#546E7A',
    status: 'complete',
    icon: '⏱️',
    description: 'Timeline of all operations',
  },
];

export const mockInitialQuery = {
  question: 'What are the key innovations in transformer architectures and pre-training methods?',
  keywords: ['transformer', 'pre-training', 'attention', 'BERT', 'GPT', 'transfer learning'],
};
